# Generated by Django 6.0.5 on 2026-05-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='amenities',
            field=models.TextField(blank=True, help_text='Amenities included for the event'),
        ),
    ]
