# Generated by Django 6.0.4 on 2026-04-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='Kakahoyan', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(default='0920 611 2718', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(default='Purok 2, Brgy. Caranoche, Sta. Catalina, Negros Oriental, 6220')),
                ('facebook_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Full Google Maps embed iframe code')),
                ('max_indoor_capacity', models.PositiveIntegerField(default=250)),
                ('max_outdoor_capacity', models.PositiveIntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
