# Generated by Django 5.0.6 on 2026-05-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_services_facilities_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityimage',
            name='facility',
        ),
        migrations.DeleteModel(
            name='ManagementTeam',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hours',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FacilityImage',
        ),
    ]
