# Generated by Django 5.0.6 on 2026-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_facility_to_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='amenityimage',
            name='image',
            field=models.ImageField(upload_to='amenities/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('bi-hearts', 'Weddings'), ('bi-balloon', 'Birthdays'), ('bi-people', 'Reunions'), ('bi-mortarboard', 'Graduation'), ('bi-briefcase', 'Company Events'), ('bi-stars', 'Socials'), ('bi-camera', 'Photo/Video'), ('bi-music-note', 'Entertainment'), ('bi-cup-hot', 'Catering'), ('bi-flower1', 'Floral')], default='bi-stars', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_maps_embed',
            field=models.TextField(blank=True),
        ),
    ]
