# Generated by Django 6.0.4 on 2026-04-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday Party'), ('reunion', 'Reunion'), ('graduation', 'Graduation Party'), ('company', 'Company Event'), ('seminar', 'Seminar / Training'), ('other', 'Other')], max_length=50)),
                ('event_date', models.DateField(blank=True, help_text='Planned event date', null=True)),
                ('expected_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional details or questions')),
                ('discussion_date', models.DateField()),
                ('discussion_time', models.TimeField()),
                ('discussion_type', models.CharField(choices=[('at_venue', 'At Kakahoyan Venue'), ('client_address', 'Client-specified Address'), ('phone_call', 'Phone Call')], max_length=20)),
                ('client_address', models.CharField(blank=True, help_text='Required if discussion type is client-specified address (must be between Sta. Catalina and Bayawan City)', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
